### PR TITLE
Security fixes

### PR DESCRIPTION
**Pull request by hepplerj**
This fixes chnm/systems#259. Tests are passing and builds completing.

### CODE REVIEW

**Comment by hepplerj** [comment]
Just kidding, I guess it doesn't fix it yet.

**Comment by hepplerj** [comment]
I see the problem with this currently failing, the govulncheck.yml is using the version in `main` for Go 1.19.

**Review by qtrinh2 — APPROVED** [review]
👍

**Review by lmullen — APPROVED** [review]
Looks great. Thanks.

**Pull request merged**
